"""Deterministic synthetic products mimicking real product structure.

Purpose: let the full pipeline run end-to-end before free-account credentials
arrive, and to validate the trajectory/hazard stack where labeled real tracks
are scarce. EVERYTHING here is synthetic: files carry `synthetic: true` in
attrs/metadata and must always be labeled as such in the UI and docs.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

from .grid import common_grid_for_box

SYNTHETIC_ATTRS = {"synthetic": 1, "source": "synthetic", "license": "generated by us (see docs/data-strategy.md D16)"}  # int flag: netCDF attrs cannot be bool


def _ice_edge_lat(day_index: int) -> float:
    """Ice edge drifts south (retreat) across the Dec-Mar window."""
    return -60.0 + 1.2 * np.sin(2.0 * np.pi * day_index / 45.0)


def make_synthetic_products(scenario: dict, out_dir: Path, days: int | None = None,
                            era5_step_deg: float = 0.5, glorys_step_deg: float = 0.25,
                            seed: int = 42) -> dict[str, Path]:
    """Generate a full synthetic scenario bundle under out_dir/raw/. Returns file paths."""
    rng = np.random.default_rng(seed)
    box = scenario["box"]
    start = pd.Timestamp(scenario["start"])
    end = pd.Timestamp(scenario["end"])
    if days:
        end = start + pd.Timedelta(days=days - 1)

    grid = common_grid_for_box(box, **scenario["grid"])
    times_daily = pd.date_range(start, end, freq="D")
    times_6h = pd.date_range(start, end, freq="6h")
    lon2d, lat2d = grid.lons(), grid.lats()
    nt = len(times_daily)

    raw = out_dir / "raw"
    raw.mkdir(parents=True, exist_ok=True)

    # ---- sea-ice concentration (%, EPSG:3412 grid) + land mask ------------------
    landmask = lat2d < (-73.2 + 0.6 * np.sin(np.deg2rad(lon2d) * 0.8))
    sic = np.empty((nt, grid.ny, grid.nx))
    for i, t in enumerate(times_daily):
        edge = _ice_edge_lat(i)
        prob = 1.0 / (1.0 + np.exp(-(lat2d - edge) / 2.0))
        prob *= 1.0 + 0.15 * np.sin(np.deg2rad(lon2d) / 20.0) * np.cos(np.deg2rad(lat2d) / 5.0)
        prob += 0.02 * rng.standard_normal((grid.ny, grid.nx))
        sic[i] = np.clip(prob * 100.0, 0.0, 100.0)
    sic[:, landmask] = np.nan
    sic_ds = xr.Dataset(
        {"sic": (("time", "y", "x"), sic),
         "landmask": (("y", "x"), landmask)},
        coords={"time": times_daily, "y": grid.y, "x": grid.x},
        attrs={**SYNTHETIC_ATTRS, "epsg": grid.epsg, "spacing_km": grid.spacing_km,
               "scenario": scenario["name"], "units": "%"},
    )
    sic_path = raw / "sic_synthetic.nc"
    sic_ds.to_netcdf(sic_path, engine="h5netcdf", invalid_netcdf=True)  # bool landmask

    # ---- sea-ice drift (48-h displacement, m) ------------------------------------
    ly, lx = grid.ny * grid.spacing_km * 1000.0, grid.nx * grid.spacing_km * 1000.0
    xx, yy = np.meshgrid(grid.x, grid.y)
    drift_u = 0.08 * np.sin(2.0 * np.pi * yy / ly) + 0.02 * np.sin(2.0 * np.pi * xx / lx)
    drift_v = -0.08 * np.cos(2.0 * np.pi * xx / lx) - 0.02 * np.cos(2.0 * np.pi * yy / ly)
    disp = np.empty((nt, grid.ny, grid.nx, 2))
    for i in range(nt):
        wob = 0.02 * np.sin(2.0 * np.pi * i / 12.0)
        disp[i, ..., 0] = (drift_u + wob) * 2 * 86400.0
        disp[i, ..., 1] = (drift_v + wob * 0.5) * 2 * 86400.0
    drift_ds = xr.Dataset(
        {"drift_x": (("time", "y", "x"), disp[..., 0]),
         "drift_y": (("time", "y", "x"), disp[..., 1])},
        coords={"time": times_daily, "y": grid.y, "x": grid.x},
        attrs={**SYNTHETIC_ATTRS, "epsg": grid.epsg, "spacing_km": grid.spacing_km,
               "drift_period_days": 2.0, "units": "m (48-h displacement)"},
    )
    drift_path = raw / "drift_synthetic.nc"
    drift_ds.to_netcdf(drift_path, engine="h5netcdf")

    # ---- ERA5-like forcing (rectilinear lon/lat, 6-hourly) ------------------------
    lat = np.arange(box["south"], box["north"] + era5_step_deg, era5_step_deg)
    lon = np.arange(box["west"], box["east"] + era5_step_deg, era5_step_deg)
    glon, glat = np.meshgrid(lon, lat)
    nt6 = len(times_6h)
    doy = times_6h.dayofyear.values.astype(float)
    u10 = 5.0 + 2.0 * np.sin(np.deg2rad(glon) / 30.0) + 0.5 * rng.standard_normal(glon.shape)
    v10 = 1.0 + 0.8 * np.cos(np.deg2rad(glat) / 20.0)
    t2m = 268.0 + 8.0 * np.cos(2.0 * np.pi * (doy - 350.0) / 365.0)[:, None, None] \
        - 0.03 * glat[None, ...]
    mslp = 98500.0 + 400.0 * np.sin(2.0 * np.pi * doy / 20.0)[:, None, None] \
        + 200.0 * np.sin(np.deg2rad(glon) / 40.0)[None, ...]
    sst = t2m - 2.0
    swh = 2.0 + 0.4 * np.abs(u10) * 0.5  # 2-D, time-invariant (broadcast in _to_3d)
    mwd = 60.0 + 20.0 * np.sin(np.deg2rad(glon) / 45.0)
    mwp = np.broadcast_to(8.0 + 1.5 * np.sin(2.0 * np.pi * doy / 15.0)[:, None, None],
                          (nt6, glon.shape[0], glon.shape[1])).copy()
    era5_vars = {
        "u10": u10, "v10": v10, "t2m": t2m, "mslp": mslp,
        "sst": sst, "swh": swh, "mwd": mwd, "mwp": mwp,
    }
    def _to_3d(name, arr):
        if arr.ndim == 2:  # time-invariant fields (u10, v10, swh, mwd)
            return ("time", "latitude", "longitude"), np.broadcast_to(arr, (nt6,) + arr.shape)
        return ("time", "latitude", "longitude"), arr  # already has time axis

    era5_ds = xr.Dataset(
        {k: _to_3d(k, v) for k, v in era5_vars.items()},
        coords={"time": times_6h, "latitude": lat, "longitude": lon},
        attrs={**SYNTHETIC_ATTRS, "scenario": scenario["name"], "crs": 4326},
    )
    era5_path = raw / "era5_synthetic.nc"
    era5_ds.to_netcdf(era5_path, engine="h5netcdf")

    # ---- GLORYS12-like ocean (rectilinear lon/lat, daily) --------------------------
    glat2 = np.arange(box["south"], box["north"] + glorys_step_deg, glorys_step_deg)
    glon2 = np.arange(box["west"], box["east"] + glorys_step_deg, glorys_step_deg)
    og2 = np.meshgrid(glon2, glat2)[1]
    uo = 0.30 + 0.20 * np.sin(np.deg2rad(og2 + 60.0) / 8.0)          # ACC-like eastward
    vo = 0.05 * np.cos(np.deg2rad(og2) / 12.0)
    thetao = 271.0 + 0.02 * og2
    zos = 0.2 * np.sin(np.deg2rad(glon2[None, :]) / 30.0) * np.ones((len(glat2), 1))
    glorys_ds = xr.Dataset(
        {k: (("time", "latitude", "longitude"), np.broadcast_to(v, (nt,) + v.shape))
         for k, v in {"uo": uo, "vo": vo, "thetao": thetao, "zos": zos}.items()},
        coords={"time": times_daily, "latitude": glat2, "longitude": glon2},
        attrs={**SYNTHETIC_ATTRS, "scenario": scenario["name"], "crs": 4326},
    )
    glorys_path = raw / "glorys_synthetic.nc"
    glorys_ds.to_netcdf(glorys_path, engine="h5netcdf")

    # ---- synthetic iceberg tracks (advected by current + wind, labeled synthetic) --
    starts = [(-68.0, 60.0), (-67.0, 30.0), (-69.5, 75.0)]
    rows = []
    for b, (slat, slon) in enumerate(starts):
        lat_i, lon_i = slat, slon
        length_m = float(rng.integers(800, 4000))
        for i, t in enumerate(times_daily):
            rows.append({"berg_id": f"SYN-{b + 1:02d}", "time": t.isoformat(),
                         "lon": round(lon_i, 4), "lat": round(lat_i, 4),
                         "length_m": length_m, "source": "synthetic"})
            if i == len(times_daily) - 1:
                break
            # nearest forcing cell
            ilat = int(np.argmin(np.abs(glat2 - lat_i)))
            ilon = int(np.argmin(np.abs(glon2 - lon_i)))
            icu, icv = uo[ilat, ilon], vo[ilat, ilon]
            iwu = u10[ilat, ilon] if ilat < len(lat) and ilon < len(lon) else 0.0
            iwv = v10[ilat, ilon] if ilat < len(lat) and ilon < len(lon) else 0.0
            ve, vn = icu + 0.03 * iwu, icv + 0.03 * iwv
            ve += rng.normal(0, 0.02)
            vn += rng.normal(0, 0.02)
            lat_i += vn * 86400.0 / 111320.0
            lon_i += ve * 86400.0 / (111320.0 * np.cos(np.deg2rad(lat_i)))
            lon_i = min(max(lon_i, box["west"] + 0.5), box["east"] - 0.5)
            lat_i = min(max(lat_i, box["south"] + 0.5), -66.0)
    bergs_path = raw / "icebergs_synthetic.csv"
    pd.DataFrame(rows).to_csv(bergs_path, index=False)

    return {"sic": sic_path, "drift": drift_path, "era5": era5_path,
            "glorys12": glorys_path, "icebergs": bergs_path}